version: "3.9"

services:
  hello-web:
    image: nginxdemos/hello:latest
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
#          - node.labels.client == true
      restart_policy:
        condition: on-failure
    ports:
      # - "5000:80"
      - published: 5001
        target: 80
        mode: host

