version: "3.9"

services:
  hello-web:
    image: nginxdemos/hello:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.client == true
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"  # Host port 5000 → Container port 80
