version: "3.9"

services:
  hello-web:
    image: nginxdemos/hello:latest
    
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.client == true
          - node.labels.celery   == true
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
