version: "3.9"

services:
  flask-api:
    build: .
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
