version: "3.9"

services:
  hello-web:
    image: nginxdemos/hello:latest
    
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
#          - node.labels.client == true
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
