version: "3.9"

services:
  hello:
    image: hello-world
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: none
