version: "3.9"

services:
  flask-api:
    image: python:3.12-slim
    container_name: flask-api
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    working_dir: /app
    command: >
      sh -c "pip install flask && 
             echo 'from flask import Flask, jsonify; app = Flask(__name__); @app.route(\"/hello\") def hello(): return jsonify({\"message\": \"Hello from Swarm!\"}); app.run(host=\"0.0.0.0\", port=5000)' > app.py && 
             python app.py"
